### PR TITLE
Fix background color prop

### PR DESCRIPTION
**Pull request by Conji**
Self explanatory. Also modified the lifecycle hook for `componentWillUnmount` to correct capitalization. This may have been causing errors, but unsure without testing from OSX.

### CODE REVIEW

**Comment by aabbccsmith** [comment]
Bump, I can't figure out how to fix this manually by editing the folder in `node_modules` so I would really appreciate this, and I know it's only two clicks.

Thank you! <3

**Comment by Conji** [comment]
@aabbccsmith if you'd like, you could checkout the branch I was working on and run the build script, outputting to the `node_modules` dir. It appears the project is more or less dead, so I may consider forking and continuing management myself.

**Comment by aabbccsmith** [comment]
> @aabbccsmith if you'd like, you could checkout the branch I was working on and run the build script, outputting to the `node_modules` dir. It appears the project is more or less dead, so I may consider forking and continuing management myself.

I'll give it a go, thanks

**Comment by aabbccsmith** [comment]
> @aabbccsmith if you'd like, you could checkout the branch I was working on and run the build script, outputting to the `node_modules` dir. It appears the project is more or less dead, so I may consider forking and continuing management myself.

Works perfectly, thank you! <3

**Pull request merged**
